### ISSUE TITLE
Crash (panic) on resume from sleep

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#191]
**gotop version:** v4.1.2   
**OS/Arch:** 5.12.15-arch1-1   
**Terminal emulator:** st   
```
10:44:21 batterygauge.go:49: error setting up batteries: [{ChargeRate:read /sys/class/power_supply/BAT0/current_now: no such device}]
panic: runtime error: slice bounds out of range [:-1]

goroutine 82 [running]:
github.com/nsf/termbox-go.Init.func1()
        /home/ser/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20200418040025-38ba6e5628f1/api.go:106 +0x36a
created by github.com/nsf/termbox-go.Init
        /home/ser/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20200418040025-38ba6e5628f1/api.go:95 +0x730
```

I believe this is related to the remote code; it happens after waking up a laptop that's collecting metrics from a remote server -- it **might** be replicable more easily by turning the network off while gotop is running while remoting.

**Comment by ivan-volnov** [comment]
In my case #220 I get the error on start. The app does not work at all.
