### ISSUE TITLE
Empty screen on startup

### ISSUE THREAD

**Issue by ivan-volnov** [xxxserxxx/gotop#220]
Empty console on start. Exits normally on mouse click or any key press.
Just installed from packages.

```
❯ pkg info gotop
gotop-4.1.3_1
Name           : gotop
Version        : 4.1.3_1
Installed on   : Sun May 22 03:18:31 2022 CST
Origin         : sysutils/gotop
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : MIT
Maintainer     : yuri@FreeBSD.org
WWW            : https://github.com/xxxserxxx/gotop
Comment        : Terminal based graphical activity monitor inspired by gtop and vtop
Annotations    :
	FreeBSD_version: 1300139
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 6.11MiB
Description    :
gotop is a terminal-based graphical activity monitor inspired by gtop and vtop.

It shows CPU/Disk/Memory/Network usage and process lists.

WWW: https://github.com/xxxserxxx/gotop
```

##### gotop version:
```
❯ gotop -V
gotop 0.0.0 (Hadean)
```
##### OS/Arch:
```
❯ uname -or
FreeBSD 13.1-RELEASE
```
##### Terminal emulator: 
Alacritty

**Comment by ivan-volnov** [comment]
Found a logfile:
```
23:14:42 remote.go:75: Remote: no remote URL provided; disabling extension
panic: runtime error: slice bounds out of range [-3:]

goroutine 1 [running]:
github.com/xxxserxxx/gotop/v4/devices.init.2.func1(0x7732c5?)
	github.com/xxxserxxx/gotop/v4/devices/mem_swap_freebsd.go:22 +0x525
github.com/xxxserxxx/gotop/v4/devices.UpdateMem(0x0?)
	github.com/xxxserxxx/gotop/v4/devices/mem.go:21 +0x76
github.com/xxxserxxx/gotop/v4/widgets.NewMemWidget(0x3b9aca00, 0x7)
	github.com/xxxserxxx/gotop/v4/widgets/mem.go:27 +0x255
github.com/xxxserxxx/gotop/v4/layout.makeWidget({{{0x0, 0x0}, {0x76f13c, 0x5}, {0x850341190, 0xa}}, 0x7, 0x0, {{0x76fa25, 0x7}, ...}, ...}, ...)
	github.com/xxxserxxx/gotop/v4/layout/layout.go:175 +0xe7
github.com/xxxserxxx/gotop/v4/layout.processRow({{{0x0, 0x0}, {0x76f13c, 0x5}, {0x850341190, 0xa}}, 0x7, 0x0, {{0x76fa25, 0x7}, ...}, ...}, ...)
	github.com/xxxserxxx/gotop/v4/layout/layout.go:136 +0x76a
github.com/xxxserxxx/gotop/v4/layout.Layout({{_, _, _}}, {{{0x0, 0x0}, {0x76f13c, 0x5}, {0x850341190, 0xa}}, 0x7, ...})
	github.com/xxxserxxx/gotop/v4/layout/layout.go:45 +0x1fe
main.run()
	github.com/xxxserxxx/gotop/v4/cmd/gotop/main.go:475 +0xb50
main.main()
	github.com/xxxserxxx/gotop/v4/cmd/gotop/main.go:391 +0x2b
```
