### ISSUE TITLE
Nvidia plugin crash

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#66]
v3.4.x candidate.  @talentlessguy reports:

```
17:56:17 cpu.go:30: GeForce GT 740M 0: strconv.Atoi: parsing "N/A": invalid syntax
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/xxxserxxx/gotop-nvidia.updateNvidiaMem(0xc0002da690, 0x0)
    /home/ser/workspace/gotop-nvidia/nvidia.go:53 +0x239
github.com/xxxserxxx/gotop/devices.UpdateMem(0xc0002da690)
    /home/ser/workspace/gotop/devices/mem.go:19 +0x84
github.com/xxxserxxx/gotop/widgets.NewMemWidget(0x3b9aca00, 0x7, 0xb79bdb)
    /home/ser/workspace/gotop/widgets/mem.go:29 +0x1c6
github.com/xxxserxxx/gotop/layout.makeWidget(0xc000026ee0, 0x19, 0xc000026ea0, 0x1e, 0xb7c238, 0xa, 0x7, 0x0, 0x0, 0x0, ...)
    /home/ser/workspace/gotop/layout/layout.go:170 +0xae
github.com/xxxserxxx/gotop/layout.processRow(0xc000026ee0, 0x19, 0xc000026ea0, 0x1e, 0xb7c238, 0xa, 0x7, 0x0, 0x0, 0x0, ...)
    /home/ser/workspace/gotop/layout/layout.go:117 +0x40e
github.com/xxxserxxx/gotop/layout.Layout(0xc00024c2a0, 0x4, 0x4, 0xc000026ee0, 0x19, 0xc000026ea0, 0x1e, 0xb7c238, 0xa, 0x7, ...)
    /home/ser/workspace/gotop/layout/layout.go:41 +0x184
main.main()
    /home/ser/workspace/gotop/cmd/gotop/main.go:403 +0x5ff
```

**Comment by talentlessguy** [comment]
Most likely the crash is caused because of a string type but not int

mb add a check or smth?

**Comment by xxxserxxx** [comment]
Close.  The crash is because I'm an idiot and didn't initialize the error array.  The code can withstand bad values, but I just missed something.

@talentlessguy , can you compile and run this code?  If you can toss these into a directory and `go run .` it, and then paste the output here, that'll help.  If you're not set up to build Go programs, let me know and I'll shoot you a link to a binary.

`go.mod`
```
module ser1.net/nvidia

require (
        github.com/GeertJohan/go.rice v1.0.0 // indirect
        github.com/facebookgo/stack v0.0.0-20160209184415-751773369052 // indirect
        github.com/k0kubun/pp v3.0.1+incompatible // indirect
        github.com/mailru/easyjson v0.7.1 // indirect
        github.com/rai-project/config v0.0.0-20190926180509-3bd01e698aad // indirect
        github.com/rai-project/logger v0.0.0-20190701163301-49978a80bf96 // indirect
        github.com/rai-project/nvidia-smi v0.0.0-20190730061239-864eb441c9ae
        github.com/rai-project/tegra v0.0.0-20181119122707-1d9901ca382b // indirect
        github.com/sirupsen/logrus v1.4.2
)
```

`main.go`
```go
package main

import (
        "fmt"
        "github.com/rai-project/nvidia-smi"
)

func main() {
        info, err := nvidiasmi.New()
        if err != nil {
                panic(err)
        }
        if info.HasGPU() {
                for i := range info.GPUS {
                        gpu := info.GPUS[i]
                        fmt.Printf("GPU %d: %s\n", i, gpu.ProductName)
                        fmt.Printf("Temp: %s\n", gpu.GpuTemp)
                        fmt.Printf("MemUtil: %s\n", gpu.MemoryUtil)
                        fmt.Printf("Total: %s\n", gpu.Total)
                        fmt.Printf("Used: %s\n", gpu.Used)
                        fmt.Printf("GpuUtil: %s\n", gpu.GpuUtil)
                }
        }
}
```

I have an updated binary set that I'll give you, but we can potentially shortcut some blind-fixing on my part if I can see some sample output from the library.

Thanks!

**Comment by talentlessguy** [comment]
@xxxserxxx here's the go program output:

```
GPU 0: GeForce GT 740M
Temp: 57 C
MemUtil: N/A
Total: N/A
Used: N/A
GpuUtil: N/A
```

**Comment by xxxserxxx** [comment]
@talentlessguy @ionlights  -- have either of you had a chance to play with this?

FYI, I'm out next week.  I will likely push v4.0.0 out before I go.  I'll release the NVidia plugin as a beta for the adventurous; since I can't test it, this may be the only way to get significant input on how it functions.  I'll explain the rationale for the version bump in the release, and I'll be back online on the 16th.

**Comment by talentlessguy** [comment]
@xxxserxxx that's very cool

btw, is there any way to avoid using `.so` files? doesn't seem good to me.

**Comment by xxxserxxx** [comment]
@talentlessguy messages crossed in flight; I hadn't seen your response when I posted.  

I see that the library isn't returning much useful information about your card; just the temperature.  I may have to use one of the other libraries.  I'll send you another code snip.

**Comment by xxxserxxx** [comment]
I should also address the decision to use Go plugins for these features.  The comment got long, so I added it as a [wiki page](https://github.com/xxxserxxx/gotop/wiki/Plugins-in-gotop).

**Comment by talentlessguy** [comment]
@xxxserxxx the problem is not with that package. I have a rather old GPU that only supports temperature sensors

**Comment by xxxserxxx** [comment]
@talentlessguy Ok. This is pretty good; it'll help bullet-proof the plugin.  Give me a moment and I'll get you new binaries.

**Comment by xxxserxxx** [comment]
@talentlessguy [tarball containing gotop (current release candidate), dummy, and nvidia plugins](https://gofile.io/?c=QD5NoV).
