### ISSUE TITLE
Wine crash

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#67]
u/HowardTheGrum on reddit reports two Windows issues:

1. gotop.exe is being flagged by Windows Defender as containing the Tisifi.B trojan
2. The following panic under Wine:

```
panic: Invalid handle.
goroutine 1 [running]:
github.com/nsf/termbox-go.clear()
`/home/ser/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190121233118-02980233997d/termbox_windows.go:681 +0x171`
github.com/nsf/termbox-go.Init(0x5f17a1, 0xa)
`/home/ser/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190121233118-02980233997d/api_windows.go:69 +0x3c2`
github.com/gizak/termui/v3.Init(0xc0000a9c10, 0xd)
`/home/ser/go/pkg/mod/github.com/gizak/termui/v3@v3.0.0/backend.go:14 +0x29`
main.main()
`/home/ser/workspace/gotop/cmd/gotop/main.go:371 +0x2b4`

```

Cursory testing with [VirusTotal](https://www.virustotal.com/gui/file/b060a88f16fd44bcb72631aafc2bdc43dee3ede57e6de7cf2d164d0d9ba0a59a/detection) reports 1/72 engine alarms.  No indication about what is triggering either virus scanner.

**Comment by xxxserxxx** [comment]
Replicated on my end:

```
panic: Invalid handle.

goroutine 1 [running]:
github.com/nsf/termbox-go.clear()
        /home/ser/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190121233118-02980233997d/termbox_windows.go:681 +0x165
github.com/nsf/termbox-go.Init(0x5dd146, 0xa)
        /home/ser/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190121233118-02980233997d/api_windows.go:69 +0x3c2
github.com/gizak/termui/v3.Init(0xc00000cba0, 0x17)
        /home/ser/go/pkg/mod/github.com/gizak/termui/v3@v3.0.0/backend.go:14 +0x29
main.main()
        /home/ser/workspace/gotop/cmd/gotop/main.go:371 +0x2b3
```

**Comment by xxxserxxx** [comment]
Ok, so... the crashes go away when gotop is run in a Windows terminal rather than directly with Wine..  To do this, one runs `wineconsole` to get a window, and then within that, run `gotop.exe`.

There are some oddities; I've seen the window go into a resizing loop, and this is fixed by putting the window in full-screen mode (where the application running in the window can't resize the window).  Also, errors are reported by Wine, such as:
```
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available..
```
But it seems to run, and Wine isn't a supported target environment, so I'm not going to look into this too much for the moment.  In any case, this indicates that `gotop` probably runs on Windows, at least to some extent.
