### ISSUE TITLE
Fails on FreeBSD 12.1

### ISSUE THREAD

**Issue by yurivict** [xxxserxxx/gotop#94]
Version 3.5.1

Fails without printing anything:
```
$ gotop
$ echo $?
2
```

The old project worked fine on FreeBSD.

**Comment by xxxserxxx** [comment]
Which was the previous version you used (that worked)?  Does FreeBSD use XDG directories?  If so, the log file will be in `~/.cache/gotop/errors.log`; if not, it may be in `~/.gotop/errors.log`.  It would be useful for me to see that.

**Comment by yurivict** [comment]
> Which was the previous version you used (that worked)?

gotop-3.0.0_1 (from the cjbassi account)


>  Does FreeBSD use XDG directories? If so, the log file will be in ~/.cache/gotop/errors.log

```
$ cat /home/yuri/.local/state/gotop/errors.log.1
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/xxxserxxx/gotop/v3/devices.update(0xc0001c2ae0, 0x4037ee02c0000000)
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/devices/temp_freebsd.go:28 +0x19a
github.com/xxxserxxx/gotop/v3/devices.UpdateTemps(0xc0001c2ae0)
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/devices/temp.go:15 +0x84
github.com/xxxserxxx/gotop/v3/widgets.(*TempWidget).update(0xc0001d40c0)
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/widgets/temp.go:118 +0x44
github.com/xxxserxxx/gotop/v3/widgets.NewTempWidget(0xc000000043, 0x8ffb17)
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/widgets/temp.go:49 +0x162
github.com/xxxserxxx/gotop/v3/layout.makeWidget(0xc000024ce0, 0x18, 0xc000024ca0, 0x1d, 0x511ece, 0xa, 0x7, 0x0, 0x0, 0x0, ...)
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/layout/layout.go:182 +0x9b8
github.com/xxxserxxx/gotop/v3/layout.processRow(0xc000024ce0, 0x18, 0xc000024ca0, 0x1d, 0x511ece, 0xa, 0x7, 0x0, 0x0, 0x0, ...)
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/layout/layout.go:117 +0x41b
github.com/xxxserxxx/gotop/v3/layout.Layout(0xc00007be00, 0x4, 0x4, 0xc000024ce0, 0x18, 0xc000024ca0, 0x1d, 0x511ece, 0xa, 0x7, ...)
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/layout/layout.go:41 +0x189
main.main()
	/usr/ports/sysutils/gotop/work/gotop-3.5.1/cmd/gotop/main.go:414 +0x6d4
```

**Comment by xxxserxxx** [comment]
Thank you.

**Comment by xxxserxxx** [comment]
I really need to find a FreeBSD VM to test this stuff on :-/

As soon as it's done buiding, I'll push out the release.

Thanks for the report.

**Comment by xxxserxxx** [comment]
@yurivict : [Release v3.5.2](https://github.com/xxxserxxx/gotop/releases/tag/v3.5.2) addresses this bug.

**Comment by yurivict** [comment]
Now it runs:
![image](https://user-images.githubusercontent.com/271906/80524155-0bfaf900-8944-11ea-8ead-b9d832eba524.png)

**Comment by xxxserxxx** [comment]
Thanks for the confirmation!
